FROM golang:1.23 AS builder

WORKDIR /app
COPY go_server/go.mod go_server/go.sum ./
RUN go mod download
COPY go_server .
RUN CGO_ENABLED=0 GOOS=linux go build -o main .

FROM gcr.io/distroless/base-debian11
WORKDIR /
COPY --from=builder /app/main .
CMD ["./main"]

