version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      -  ./init_schemas.sql:/docker-entrypoint-initdb.d/init_schemas.sql

  back:
    build:
      context: ./back
    environment:
      DATABASE_URL: ${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    ports:
      - "8000:8000"

  front:
    build:
      context: ./front
    environment:
      API_ENDPOINT: ${API_ENDPOINT}
    ports:
      - "8501:8501"
    depends_on:
      - back

volumes:
  pg_data:

