FROM python:3.12-slim

WORKDIR /app

COPY ./back /app/back

RUN pip install /app/back

RUN pip install -r /app/back/requirements.txt

CMD ["uvicorn", "back.main:app", "--host", "0.0.0.0", "--port", "8000"]

