// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: comments.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM param.activity_comments
WHERE comment_id = $1
AND activity_id = $2
`

type DeleteCommentParams struct {
	CommentID  int32
	ActivityID int64
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) error {
	_, err := q.db.ExecContext(ctx, deleteComment, arg.CommentID, arg.ActivityID)
	return err
}

const getAllComments = `-- name: GetAllComments :many
SELECT comment_id, u.username, comment
  
FROM param.activity_comments as ac
LEFT JOIN settings.users as u
ON u.user_id = ac.user_id
WHERE activity_id = $1
`

type GetAllCommentsRow struct {
	CommentID int32
	Username  sql.NullString
	Comment   string
}

func (q *Queries) GetAllComments(ctx context.Context, activityID int64) ([]GetAllCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllComments, activityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllCommentsRow
	for rows.Next() {
		var i GetAllCommentsRow
		if err := rows.Scan(&i.CommentID, &i.Username, &i.Comment); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const postComment = `-- name: PostComment :exec
INSERT INTO param.activity_comments(activity_id, user_id, comment)
VALUES (
  $1, $2, $3
)
`

type PostCommentParams struct {
	ActivityID int64
	UserID     uuid.UUID
	Comment    string
}

func (q *Queries) PostComment(ctx context.Context, arg PostCommentParams) error {
	_, err := q.db.ExecContext(ctx, postComment, arg.ActivityID, arg.UserID, arg.Comment)
	return err
}

const updateComment = `-- name: UpdateComment :exec
UPDATE param.activity_comments
SET comment = $1
WHERE comment_id = $2
AND activity_id = $3
`

type UpdateCommentParams struct {
	Comment    string
	CommentID  int32
	ActivityID int64
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) error {
	_, err := q.db.ExecContext(ctx, updateComment, arg.Comment, arg.CommentID, arg.ActivityID)
	return err
}
