name: Docker Image CI

on:
  push:
    tags:
      - 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Frontend Image
      run: docker build -t endurace_reporting:front.${{ github.ref_name }} -f front/Dockerfile .

    - name: Build Backend Image
      run: docker build -t endurace_reporting:backend.${{ github.ref_name }} -f back/Dockerfile .

    - name: Push Frontend Image
      run: |
        docker tag myrepo:front.${{ github.ref_name }} myrepo:front.latest
        docker push myrepo:front.${{ github.ref_name }}
        docker push myrepo:front.latest

    - name: Push Backend Image
      run: |
          docker tag endurace_reporting:backend.${{ github.ref_name }} myrepo:backend.latest
          docker push endurace_reporting:backend.${{ github.ref_name }}
          docker push endurace_reporting:backend.latest
