name: Docker Image CI

on:
  push:
    tags:
      - "v*"

# on:
#   pull_request:
#     branches:
#       - main
#     types:
#       - closed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Frontend Image
      run: docker build -t deretz/endurace_reporting:frontend.${{ github.ref_name }} -f front/Dockerfile front/

    - name: Build Backend Image
      run: docker build -t deretz/endurace_reporting:backend.${{ github.ref_name }} -f back/Dockerfile back/

    - name: Build GO Image
      run: docker build -t deretz/endurace_reporting:backend.${{ github.ref_name }} -f Dockerfile.go_server .

    - name: Build goose Image
      run: docker build -t deretz/endurace_reporting:goose.${{ github.ref_name }} -f front/Dockerfile.goose .

    - name: Push Frontend Image
      run: |
        docker tag deretz/endurace_reporting:frontend.${{ github.ref_name }} deretz/endurace_reporting:frontend.latest
        docker push deretz/endurace_reporting:frontend.${{ github.ref_name }}
        docker push deretz/endurace_reporting:frontend.latest

    - name: Push Backend Image
      run: |
          docker tag deretz/endurace_reporting:backend.${{ github.ref_name }} deretz/endurace_reporting:backend.latest
          docker push deretz/endurace_reporting:backend.${{ github.ref_name }}
          docker push deretz/endurace_reporting:backend.latest

    - name: Push GO Image
      run: |
        docker tag deretz/endurace_reporting:go_server.${{ github.ref_name }} deretz/endurace_reporting:go_server.latest
        docker push deretz/endurace_reporting:go_server.${{ github.ref_name }}
        docker push deretz/endurace_reporting:go_server.latest

    - name: Push goose Image
      run: |
        docker tag deretz/endurace_reporting:goose.${{ github.ref_name }} deretz/endurace_reporting:goose.latest
        docker push deretz/endurace_reporting:goose.${{ github.ref_name }}
        docker push deretz/endurace_reporting:goose.latest
